---
- name: check_repos
  stat:
    path: "{{ git_repo_dest }}"
  register: check_repos
- name: git clone
  git:
    repo: "{{ git_repo_url }}"
    dest: "{{ git_repo_dest }}"
    version: "{{ git_branch_name }}"
- block:
  - name: disable git check permissions
    shell: "cd {{ git_repo_dest }}; git config core.filemode false"
  - name: change project permissions
    file:
      path: "{{ git_repo_dest }}"
      recurse: yes
      state: directory
      owner: nginx
      group: laravel
      mode: '777'
  when: not check_repos.stat.exists
- name: composer install
  become: no
  shell: "cd {{ git_repo_dest }}; composer install "
- name: check_env
  stat:
    path: "{{ git_repo_dest }}/.env"
  register: check_env
- name: create .env
  template:
    src: env.j2
    dest: "{{ git_repo_dest }}/.env"
    owner: nginx
    group: laravel
    mode: 0777
  when: not check_env.stat.exists
- name: generate APP_KEY
  become: no
  shell: "cd {{ git_repo_dest }};php artisan key:generate"
  when: not check_env.stat.exists
- name: migration DB
  shell: "cd {{ git_repo_dest }}; php artisan migrate"
  register: migrate_result
  changed_when: "migrate_result.stdout != 'Nothing to migrate.'"
  when: ansible_facts['distribution'] == "Amazon"
