- name: check composer
  stat: path=/usr/local/bin/composer
  register: composer_bin
  tags: composer
- block:
  - name: download composer
    get_url:
      url: https://getcomposer.org/installer
      dest: /tmp/composer-setup.php
  - name: set home
    shell: export HOME=/root
  - name: set composer home
    shell: export COMPOSER_HOME=/root
  - name: install composer
    shell: php /tmp/composer-setup.php
  - name: rename composer.phar to composer
    shell: mv /tmp/composer.phar /usr/local/bin/composer
  - name: make composer executable
    file:
      path: /usr/local/bin/composer
      mode: a+x
      state: file
  when: not composer_bin.stat.exists
  tags: composer

